wave2/web/WebTrack/SportStore/Models/PagingInfoViewModel.cs
using System;

namespace SportStore.Models
{
    public class PagingInfoViewModel
    {
        public int TotalItems { get; set; }


        public int ItemsPerPage { get; set; }


        public int CurrentPage { get; set; }


        public int TotalPages => (int) Math.Ceiling((double) TotalItems / ItemsPerPage);
    }
}

wave2/web/WebTrack/SportStore/Models/ProductDto.cs
namespace SportStore.Models
{
    // This is actually returned from our server and we cannot mutate it.
    public class ProductDto
    {
        public int Id { get; set; }


        public decimal Price { get; set; }


        public string Category { get; set; }
    }



    // Pure: map to vm.
    public class SomeProductMappedViewModel
    {
        public int ProductId { get; set; }


        public decimal Price { get; set; }


        public string Category { get; set; }


        public string FriendlyCatalogName => $"Id: {ProductId} -- €{Price:00.00}";
    }


    public class SomeProductMappedViewModelMapper
    {
        public SomeProductMappedViewModel Map(ProductDto dto)
        {
            var vm2 = new SomeProductContained2ViewModel(dto);
            vm2.Price = 666m;

            return
                new SomeProductMappedViewModel
                {
                    ProductId = dto.Id,
                    Price = dto.Price,
                    Category = dto.Category
                };

            // Automapper.
            //var vm = autoMapper.Map<SomeProductMappedViewModel>(dto);
        }
    }



    // Pure: contain variant 1
    public class SomeProductContained1ViewModel
    {
        public int ProductId { get; set; }


        public decimal Price { get; set; }


        public string Category { get; set; }


        public string FriendlyCatalogName => $"Id: {ProductId} -- €{Price:00.00}";



        public SomeProductContained1ViewModel(ProductDto dto)
        {
            ProductId = dto.Id;
            Price = dto.Price;
            Category = dto.Category;
        }
    }



    // Pure: contain variant 2
    public class SomeProductContained2ViewModel
    {
        private readonly ProductDto _dto;



        // Not settable.
        public int ProductId => _dto.Id;


        // Allows set.
        public decimal Price
        {
            get { return _dto.Price; }
            set { _dto.Price = value; }
        }


        public string Category => _dto.Category;


        public string FriendlyCatalogName => $"Id: {ProductId} -- €{Price:00.00}";



        public SomeProductContained2ViewModel(ProductDto dto)
        {
            _dto = dto;
        }
    }



    // Pragmatic
    public class SomeProductPragmaticViewModel
    {
        public ProductDto ProductDto { get; }



        public string FriendlyCatalogName => $"Id: {ProductDto.Id} -- €{ProductDto.Price:00.00}";



        public SomeProductPragmaticViewModel(ProductDto dto)
        {
            ProductDto = dto;
        }
    }
}

wave2/web/WebTrack/SportStore/Models/ProductListViewModel.cs
using System.Collections.Generic;
using SportStore.Domain.Model;


namespace SportStore.Models
{
    public class ProductListViewModel
    {
        public IEnumerable<Product> Products { get; set; }


        public PagingInfoViewModel PagingInfo { get; set; }


        public string CurrentCategory { get; set; }
    }
}

wave2/web/WebTrack/SportStore/Controllers/NavigationController.cs
using System.Web.Mvc;
using SportStore.Domain.Repositories.Contracts;


namespace SportStore.Controllers
{
    public class NavigationController
        : Controller
    {
        private readonly IProductRepository _productRepository;



        public NavigationController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }


        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            var categories = _productRepository.GetAllCategories();

            return PartialView(categories);
        }
    }
}

wave2/web/WebTrack/SportStore/Controllers/ProductController.cs
using System.Web.Mvc;
using SportStore.Domain.Repositories.Contracts;
using SportStore.Models;


namespace SportStore.Controllers
{
    public class ProductController
        : Controller
    {
        private readonly IProductRepository _productRepository;


        public int _pageSize = 2;



        public ProductController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }


        public ActionResult List(string category, int page = 1)
        {
            //var products = _productRepository.GetAll();
            var products = _productRepository.GetAll(category, page, _pageSize);

            var totalItems = _productRepository.GetTotalCount(category);

            var pagingInfo =
                new PagingInfoViewModel
                {
                    TotalItems = totalItems,
                    ItemsPerPage = _pageSize,
                    CurrentPage = page
                };

            var productListViewModel =
                new ProductListViewModel
                {
                    Products = products,
                    PagingInfo = pagingInfo,
                    CurrentCategory = category
                };

            return View(productListViewModel);
        }
    }
}

wave2/web/WebTrack/SportStore/Views/Navigation/Menu.cshtml
@model IEnumerable<string>
    
@Html.ActionLink("All", "List", "Product", null, new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var currentCategory in Model)
{
    @Html.RouteLink(currentCategory, new { controller = "Product", action = "List", category = currentCategory, page = 1 }, new { @class = "btn btn-block btn-default btn-lg " + (currentCategory == ViewBag.SelectedCategory ? "btn-primary" : "") })
}

wave2/web/WebTrack/SportStore/Views/Product/List.cshtml
@using SportStore.Domain
@using SportStore.Models
@using SportStore.HtmlHelpers
@model ProductListViewModel

@{
    ViewBag.Title = "Products";
}

@foreach (var product in Model.Products)
{
    @Html.Partial("ProductSummary", product)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, currentPage => Url.Action("List", new { page = currentPage, category = Model.CurrentCategory }))
</div>

wave2/web/WebTrack/SportStore/Views/Shared/ProductSummary.cshtml
@model SportStore.Domain.Model.Product
    
<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    <span class="lead">
        @Model.Description
    </span>
</div>

wave2/web/WebTrack/SportStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <title>@ViewBag.Title - Sport STORE</title>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sport STORE", "List", "Product", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Navigation")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>